apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: ${GKE_NAMESPACE}
type: Opaque
stringData:
  VITE_SUPABASE_URL: ${SUPABASE_URL}
  VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
